### ISSUE TITLE
Deprecated plugin warning when using Pongo to test custom plugins -- need help in eliminating the dependency.

### ISSUE THREAD

**Issue by morals415** [Kong/kong-pongo#105]
(I am opening this issue on behalf of an enterprise customer)

EE 1.5.0.4

While running pongo on some custom plugins developed internally, we received the following warning for each plugin's spec:

`[lua] plugins.lua:231: load_plugin(): plugin 'route-by-header' has been deprecated, context: ngx.timer`

Note: all our test cases passed, but we do not wish to incur additional technical debt associated with this deprecation, provided we can remediate it at this time.

I'm looking for some suggestions on how to debug the introduction of this dependency into the code tree so that I can understand how to eliminate it.

**Comment by Tieske** [comment]
it is a standard warning when starting Kong, the deprecated plugin is still part of "bundled", as specified in the `KONG_PLUGINS=bundled` environment variable. Since that is all part of a specific Kong release, there is little you can do about it.

An option would be to run Kong `KONG_PLUGINS` set to something that doesn't include those plugins, but then at some point in the future it will reappear based on other depreacted plugins.

**Comment by Tieske** [comment]
in your test files you can specify which plugins to add; https://github.com/Kong/kong-plugin/blob/master/spec/myplugin/02-access_spec.lua#L34
Just drop `bundled` and only add the plugins you need, or better; add the plugins you also have availabel in your production enviornment to mimick that as close as possible.

**Comment by Tieske** [comment]
@morals415 can we close this?
