### ISSUE TITLE
Tagged release versions

### ISSUE THREAD

**Issue by esatterwhite** [Kong/kong-pongo#237]
Being that the install process is documented as cloning the repo, it would be nice to have tag denoting fixed  + stable points in time.
It might make sense to have the tags mirror the highest version of kong that is support at that time.

`2.6.0` support kong <= `2.6.0`

**Comment by Tieske** [comment]
@curiositycasualty any opinions on this?

I don't think that matching Kong versions makes sense, historically, there have been hardly any breaking changes wrt Kong versions. Only very minor changes in Pongo behaviour itself.

My 2cts: just tag 1.0.0, and take it from there.

Anyway since everybody is for now cloning the repo, we need to put up a warning that we're switching to versioning, and then give it at least 6 months before introducing any breaking changes on the master branch.

**Comment by Tieske** [comment]
see #252

**Comment by curiositycasualty** [comment]
Sorry about letting this languish.

A tag of any sort definitely seems like a good place to start.
As a project, there's probably a discussion to be had about what different semver changes might mean to Pongo.
But a tag is a good place to start.

**Comment by curiositycasualty** [comment]
Sorry about letting this languish @Tieske 

A tag of any sort definitely seems like a good place to start.
As a project, there's probably a discussion to be had about what different semver changes might mean to Pongo.
But a tag is a good place to start.

**Comment by Tieske** [comment]
version 1.0.0 released!
