### ISSUE TITLE
Postgres version

### ISSUE THREAD

**Issue by james-callahan** [Kong/kong-pongo#26]
The readme says that the default postgres version is 9.5, and the examples use 9.4

Isn't the minimum supported version 9.6? And shouldn't testing be encouraged with newer releases?

**Comment by Tieske** [comment]
I remved the 9.4 versions, but after discussion the thought is that we stick to the old versions for defaults. Because unknowingly using newer DB features seems a bigger risk than new DB versions dropping existing functionality.

And if DB's are used, using tests against each probably makes sense and is always a (manual) config element in CI setup
