### ISSUE TITLE
`--no-<service name>` to `pongo run` has no effect when running tests 

### ISSUE THREAD

**Issue by shettyh** [Kong/kong-pongo#268]
Hi,

I am trying to avoid running `cassandra` strategy during test cases and only run test cases on `postgres`. 

`pongo run --no-cassandra ....` -> this still runs test cases with cassandra and fails as the cassandra container is not running

Please let me know how can i resolve this

**Comment by flrgh** [comment]
Hiya @shettyh,

The `--no-<service name>` flags only control which containers are/aren't started up and don't really interact with busted in a meaningful way. The common pattern in Kong's codebase is to [tag tests according to db strategy](https://github.com/Kong/kong/blob/4f4af4045d23b1251aa91990293a9f77a37ec11c/spec/03-plugins/36-request-transformer/02-access_spec.lua#L15-L16) so that they can be targeted explicitly. Assuming you are following this pattern, you should be able to pass in `--tags postgres` to pongo/busted to omit the cassandra tests. Can you give that a try and see if it works?

**Comment by Tieske** [comment]
@flrgh correct. An alternative could be to use the opposite; `--exclude-tags=cassandra`

```
pongo up --no-cassandra
pongo run --exclude-tags=cassandra
```

**Comment by shettyh** [comment]
@flrgh @Tieske thanks for the quick response. Tried the suggested alternatives `pongo run --no-postgres --tags=cassandra -v -o gtest ./spec/` -> This still try to run test cases in postgres, not sure if i am doing something wrong. Following the same pattern as mentioned above for writing test cases

**Comment by shettyh** [comment]
Thanks it works in CI. Somehow it didn't work in my local setup

**Comment by Tieske** [comment]
`--no-postgres` doesn't work with the `run` command. Only with the `up` and `down` commands. To permanently turn them of add them to the `.pongo/pongorc` file
