### ISSUE TITLE
Conflicting ports on pongo up --expose

### ISSUE THREAD

**Issue by iwaffles** [Kong/kong-pongo#307]
Hi there!

Trying to run `pongo up --expose` and it seems that since port 7000 is already in use, it fails. I believe this port is already in use on macOS. 

Is there a supported method of getting around this so I can still expose the ports? Perhaps a flag or something to configure them? I took a look at the source but didn't spot anything.

**Comment by Tieske** [comment]
port 7000 is a default port used by Cassandra. At some point Apple started using it for Apple airplay. Here's some info to get around it: https://github.com/cookiecutter/cookiecutter-django/issues/3499#issue-1089496796


We cannot make breaking changes now. In a couple of months we might. Escpecially since Cassandra support is being deprecated in Kong 3 we should be able to make some changes then.

**Comment by Tieske** [comment]
To adjust Pongo; you could disable this line: https://github.com/Kong/kong-pongo/blob/d10eb09f8d0de6856fb022555cd2dd9b56695f23/assets/docker-compose.yml#L23 (if you're not using Cassandra)

**Comment by Tieske** [comment]
@iwaffles did that solve your issue?

**Comment by iwaffles** [comment]
It did, thanks @Tieske!
