### ISSUE TITLE
--no-cassandra errors `could not resolve any of the provided Cassandra contact points`

### ISSUE THREAD

**Issue by sanjsharma** [Kong/kong-pongo#330]
I am getting following error while running pongo. All the tests run, pass and the error appears after the test run has completed with results. 

Command 
```
KONG_VERSION=2.8.1 POSTGRES=13 pongo run --no-cassandra
```

ERROR:- 
```
my-pugin: (access) [#cassandra] lazy_setup
./spec/helpers.lua:392: could not resolve any of the provided Cassandra contact points (cassandra_contact_points = 'pongo-19daec31-cassandra.pongo-19daec31')
ERROR: 1
```

**Comment by Tieske** [comment]
That is because you start the environment without Cassandra when passing `--no-cassandra`, yet in your plugins tests you still run the tests against Cassandra, and hence it will not be able to connect.

looks like you're using the plugin template. See this recent commit on disabling cassandra from the tests: https://github.com/Kong/kong-plugin/commit/05d55447ee4b94dedf7a109ece8da5114dc1a44e#diff-f1a7beab0ea3822e602403b6560d02dbbd14359ed5c5efaf9ec0d2983d173bd2

**Comment by sanjsharma** [comment]
Yes removing the Cassandra part from `helpers.all_strategies()` solved the issue.
