### ISSUE TITLE
Building Python from source takes too long on Mac M1

### ISSUE THREAD

**Issue by hanshuebner** [Kong/kong-pongo#349]
On M1 Macs using Docker Desktop, building Python from source takes much too long - It is already annoyingly slow on Linux/amd64, but on Mac/M1 it takes in the order of 25 minutes, which is unbearable.

A few options that I could think of:

 - Ship outdated httpie on Ubuntu 16.04
 - Drop support for Ubuntu 16.04
 - Publish our own .deb files for Python 3.9 and httpie on Ubuntu 16.04

Other ideas?

**Comment by windmgc** [comment]
I'm wondering why is httpie a must in pongo?

**Comment by windmgc** [comment]
If we must keep httpie, then +1 for dropping support for Ub 16.04 as it is already passed EOL

**Comment by nbialostosky** [comment]
Adding on here, we recently saw a drastic increase in the time it takes to test our custom plugins with Pongo with the newest version release (2.0.0).

Within CI (CircleCI specifically) on `1.3.0` it took about ~2 mins to spin everything up and run our tests.

With `2.0.0` it now takes anywhere between 8-9 minutes to spin up and test. It does seem like part of the issue is the Python install.

Is there anything that can be done with the switch to Ubuntu to get things sped up?

**Comment by hanshuebner** [comment]
Fixed by https://github.com/Kong/kong-pongo/pull/357
