### ISSUE TITLE
pongo run failed

### ISSUE THREAD

**Issue by NICK-DUAN** [Kong/kong-pongo#85]
`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/assets/docker-compose.yml'`

when i run `pongo run`，i will get this error, and i don't know how to fix it

**Comment by Tieske** [comment]
looks like you installed it wrong.

From `/usr/local/bin/assets/docker-compose.yml` it seems that your main pongo script is located at `/usr/local/bin`

You should clone the Pongo repo, and only create a symlink in your system path, called `pongo` pointing to `<cloned repo>/pongo.sh`

Unless your OS reports the `realpath` of the symlink instead of the script it points to.

**Comment by NICK-DUAN** [comment]
> looks like you installed it wrong.
> 
> From `/usr/local/bin/assets/docker-compose.yml` it seems that your main pongo script is located at `/usr/local/bin`
> 
> You should clone the Pongo repo, and only create a symlink in your system path, called `pongo` pointing to `<cloned repo>/pongo.sh`
> 
> Unless your OS reports the `realpath` of the symlink instead of the script it points to.

thanks a lot, it work for me. I used the wrong installation method before
